server:
    port: 8081
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/klinikpro # (o 5432 según lo que quedó)
        username: klinik
        password: klinik_dev
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
management:
    endpoints:
        web:
            exposure:
                include: health,info
app:
    version: VF1-0.0.1
security:
    jwt:
        secret: "CAMBIA_ESTO_por_una_cadena_larga_de_al_menos_64_caracteres_aleatorios_123456"
        expiration-ms: 86400000   # 24 h
