package systems.cytohelix.klinikpro_vf;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.UUID;

import org.junit.jupiter.api.Test;

import io.jsonwebtoken.Claims;
import systems.cytohelix.klinikpro_vf.auth.JwtService;
import systems.cytohelix.klinikpro_vf.auth.Role;
import systems.cytohelix.klinikpro_vf.auth.User;

class JwtServiceTest {

    @Test
    void generateAndParse() {
        JwtService jwt = new JwtService("test-secret-key-for-unit-tests-only-min-32-chars-xx", 3_600_000L);
        User u = new User();
        // id is generated by JPA; for unit test set via reflection-free path by using claims from generate
        // JwtService only needs tenant/branch/role/email/name and id for subject — use a stub with id set via package access isn't possible.
        // Work around: set fields that generate() reads; id may be null → NPE. Assign with a real UUID through a minimal subclass.
        TestUser tu = new TestUser();
        tu.forceId(UUID.fromString("11111111-1111-1111-1111-111111111111"));
        tu.setTenantId(UUID.fromString("22222222-2222-2222-2222-222222222222"));
        tu.setBranchId(UUID.fromString("33333333-3333-3333-3333-333333333333"));
        tu.setEmail("a@b.com");
        tu.setFullName("Admin");
        tu.setRole(Role.ADMIN);

        String token = jwt.generate(tu);
        Claims c = jwt.parse(token);
        assertThat(c.getSubject()).isEqualTo("11111111-1111-1111-1111-111111111111");
        assertThat(c.get("tenantId", String.class)).isEqualTo("22222222-2222-2222-2222-222222222222");
        assertThat(c.get("role", String.class)).isEqualTo("ADMIN");
    }

    /** Minimal User with settable id for pure unit test. */
    static class TestUser extends User {
        void forceId(UUID id) {
            try {
                var f = User.class.getDeclaredField("id");
                f.setAccessible(true);
                f.set(this, id);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }
}
